# Generated by Django 5.1.5 on 2025-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
