# Generated by Django 5.1.5 on 2025-02-02 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_request', '0002_alter_leave_end_date_alter_leave_start_date'),
        ('user', '0009_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='user.employee'),
        ),
    ]
