# Generated by Django 5.1.5 on 2025-01-29 09:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
