# Generated by Django 5.1.5 on 2025-01-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_employee_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
